### ISSUE TITLE
can't compile on CentOS

### ISSUE THREAD

**Issue by ingber** [jordansissel/xdotool#15]
I ZIP'd the latest code, and modified the makefile:
DEFAULT_LIBS=-L/usr/lib -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXtst -lXinerama
### DEFAULT_LIBS=-L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXtst -lXinerama

since Xtst is under /usr/lib
/usr/lib/libXtst.so.6
/usr/lib/libXtst.so.6.1.0
/usr/lib64/libXtst.so.6
/usr/lib64/libXtst.so.6.1.0

I tried to compile, but get:
pod2man -c "" -r "" xdotool.pod > xdotool.1
sh version.sh --header > xdo_version.h
cc -pipe -O2 -pedantic -Wall -W -Wundef -Wendif-labels -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-align -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wdisabled-optimization -Wno-missing-field-initializers -g  -std=c99 -I/usr/X11R6/include -I/usr/local/include -fPIC -c xdo.c
cc -pipe -O2 -pedantic -Wall -W -Wundef -Wendif-labels -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-align -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wdisabled-optimization -Wno-missing-field-initializers -g  -std=c99 -I/usr/X11R6/include -I/usr/local/include -fPIC -c xdo_search.c
cc  -shared -Wl,-soname=libxdo.so.2 xdo.o xdo_search.o -o libxdo.so -lrt -L/usr/lib -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXtst -lXinerama
/usr/bin/ld: skipping incompatible /usr/lib/librt.so when searching for -lrt
/usr/bin/ld: skipping incompatible /usr/lib/librt.a when searching for -lrt
/usr/bin/ld: skipping incompatible /usr/lib/libX11.so when searching for -lX11
/usr/bin/ld: cannot find -lXtst
collect2: ld returned 1 exit status
make: **\* [libxdo.so] Error 1

Any suggestions?

Thanks.

Lester

P.S.:

I also could not compile on Ubuntu 12.04:
pod2man -c "" -r "" xdotool.pod > xdotool.1
sh version.sh --header > xdo_version.h
cc -pipe -O2 -pedantic -Wall -W -Wundef -Wendif-labels -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-align -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wdisabled-optimization -Wno-missing-field-initializers -g  -std=c99 -I/usr/X11R6/include -I/usr/local/include -fPIC -c xdo.c
xdo.c:29:34: fatal error: X11/extensions/XTest.h: No such file or directory
compilation terminated.
make: **\* [xdo.o] Error 1
